### ISSUE TITLE
Work with Episode 63 

### ISSUE THREAD

**Issue by spotlessmind1** [citizen-cosmos/Podcast#26]

**Comment by spotlessmind1** [comment]
We need this episode to be done till Monday. You need prepare following by this episode : 

- [ ] Transcript
- [ ] projects that was mentioned
- [ ] themes that was rised
- [ ] 5-6 interesting quotes (the length maximum 5-7 sec) 
- [ ] Article - this could be done till Friday.
